apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-minikube-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-minikube-app-pod
  template:
    metadata:
      labels:
        app: go-minikube-app-pod
    spec:
      containers:
        - name: go-app
          image: guilhermelinosp/go-minikube-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-minikube-service
spec:
  type: NodePort
  selector:
    app: go-minikube-app-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
